### ISSUE TITLE
x509: certificate signed by unknown authority

### ISSUE THREAD

**Issue by santa2021** [Snawoot/hola-proxy#10]
Hi, I'm trying to run a program on my router, but I get an error:

credservice.go:34: CRITICAL Configuration bootstrap failed: Post "https://client.hola.org/client_cgi/background_init?uuid=6023b29cedd040baa7220dfbafc8a47d": x509: certificate signed by unknown authority
MAIN    : 2021/01/04 17:28:31 main.go:104: CRITICAL Unable to instantiate credential service: Post "https://client.hola.org/client_cgi/background_init?uuid=6023b29cedd040baa7220dfbafc8a47d": x509: certificate signed by unknown authority
How can this problem be solved?

P.S. On desktop program work fine

**Comment by Snawoot** [comment]
Hi!

Looks like system on your router lacks CA certificates and can't verify TLS connections on its own. If it's something like OpenWRT, you can install CA bundle like this:

```sh
opkg update && opkg install ca-bundle
```

Alternatively, you may just put CA cacert.pem from [here](https://curl.se/docs/caextract.html) into one of these locations:

```
/etc/ssl/certs/ca-certificates.crt
/etc/pki/tls/certs/ca-bundle.crt
/etc/ssl/ca-bundle.pem
/etc/pki/tls/cacert.pem
/etc/pki/ca-trust/extracted/pem/tls-ca-bundle.pem
/etc/ssl/cert.pem
```
