### ISSUE TITLE
Can't connect on Windows 10?

### ISSUE THREAD

**Issue by oknchm** [Snawoot/hola-proxy#101]
Hello, I'm trying to use hola-proxy on Windows 10. It looks like it has connected successfully, but when I check my IP location or visit a geo-restricted site (US for example), they say I'm still on my original location. What else should I change or add to my settings (on my computer or hola-proxy). Thank you!

```
C:\Users\mycomputer\Desktop>hola-proxy.windows-amd64.exe -timeout 30s -country us
MAIN    : 2023/09/14 08:01:32 main.go:192: WARNING  Detected latest extension version: "1.215.40". Pass -ext-ver parameter to skip resolve and speedup startup
MAIN    : 2023/09/14 08:01:32 main.go:200: INFO     hola-proxy client version v1.11.0 is starting...
MAIN    : 2023/09/14 08:01:32 main.go:201: INFO     Constructing fallback DNS upstream...
MAIN    : 2023/09/14 08:01:32 main.go:208: INFO     Initializing configuration provider...
MAIN    : 2023/09/14 08:01:43 main.go:222: INFO     Endpoint: https://zagent1635.hola.org:22225
MAIN    : 2023/09/14 08:01:43 main.go:223: INFO     Starting proxy server...
MAIN    : 2023/09/14 08:01:43 main.go:225: INFO     Init complete.
```

**Comment by Snawoot** [comment]
Hi! You've got to configure your browser to use a proxy. Check the program description: https://github.com/Snawoot/hola-proxy#readme

Also check out Proxy SwitchyOmega browser extension for a convenient way of controlling proxy in your browser.

**Comment by aloevera88** [comment]
> Hi! You've got to configure your browser to use a proxy. Check the program description: https://github.com/Snawoot/hola-proxy#readme
I have the same problem as @oknchm and I can't find the part that explains how this works with a browser in the program description.
