### ISSUE TITLE
It's stuck at this, how to use this further?

### ISSUE THREAD

**Issue by Auditormadness9** [Snawoot/hola-proxy#103]
![image](https://github.com/Snawoot/hola-proxy/assets/71278545/d1d78813-46fa-4ac7-a6fd-d418622a7a52)

**Comment by Snawoot** [comment]
Hi!

Check out [documentation on the main page](https://github.com/Snawoot/hola-proxy#readme):

> Standalone Hola proxy client. Just run it and it'll start a plain HTTP proxy server forwarding traffic through Hola proxies of your choice. By default the application listens on 127.0.0.1:8080.

**Comment by Auditormadness9** [comment]
I am on Windows. There's no way for me to choose anything besides run the exe and get this screen.

**Comment by reneManqueros** [comment]
You can run the binary via powershell or CMD that way you can pass in extra params OR just double click it which will give you the defaults.
Once you are at that screen the proxy is already working, so your next step is either set it as a system proxy on your network settings or per application, you can easily google for: how to use a proxy on chrome or how to set a windows 11 proxy.
