### ISSUE TITLE
Support Hola Free Account to Bypass Ban

### ISSUE THREAD

**Issue by gashtal** [Snawoot/hola-proxy#109]
I have noticed that quickly switching the proxy a few times will result in a temporary IP ban. The same happens with the actual Hola add-on in browser. However, the ban can be bypassed in browser by logging into a free Hola account (the ad-on will force opens the login screen and won't turn on until the user logs into an account). Is it possible to add support for free Hola accounts so that the ban can also be bypassed with hola-proxy?

**Comment by Snawoot** [comment]
Some sort of state-preserving login is possible like it is implemented in [windscribe-proxy](https://github.com/Snawoot/windscribe-proxy), but I'm not planning to work myself on this feature. If anyone wants to implement it, I'll review and accept pull request.
