### ISSUE TITLE
credservice.go fails to run.

### ISSUE THREAD

**Issue by Denniso2** [Snawoot/hola-proxy#11]
The script was working just fine for many days but today I started getting this error 
`MAIN    : 2021/02/16 20:23:48 main.go:95: INFO     Constructing fallback DNS upstream...
MAIN    : 2021/02/16 20:23:48 main.go:101: INFO     Initializing configuration provider...
CRED    : 2021/02/16 20:23:49 credservice.go:34: CRITICAL Configuration bootstrap failed: invalid character '<' looking for beginning of value
MAIN    : 2021/02/16 20:23:49 main.go:104: CRITICAL Unable to instantiate credential service: invalid character '<' looking for beginning of value`

**Comment by Snawoot** [comment]
Hi!

I've seen such behavior about an hour ago, but now it seems working. Probably there was temporary issue on Hola backend.
