### ISSUE TITLE
Program crash [v1.13.3 windows-386]

### ISSUE THREAD

**Issue by jaejunks** [Snawoot/hola-proxy#119]
Starting `hola-proxy.windows-386.exe` version 1.13.3 even with just `--help` command line switch, it crashes with below output.

```
Exception 0xc0000005 0x8 0x0 0x0
PC=0x0

runtime.asmstdcall(0x20)
	runtime/sys_windows_386.s:44 +0x2a fp=0x18fe28 sp=0x18fe24 pc=0x47211a
eax     0x8
ebx     0xf34670
ecx     0x0
edx     0x18fe58
edi     0x18fe2c
esi     0x18fe8c
ebp     0x18fe2c
esp     0x18fe20
eip     0x0
eflags  0x10206
cs      0x23
fs      0x53
gs      0x2b

```
This problem applies to version 1.13.1 to 1.13.3. Both 32-bit and 64-bit versions of the releases. Version 1.12.1 works fine.

**Comment by Snawoot** [comment]
Hi! Which Windows version you are using?

**Comment by jaejunks** [comment]
Windows 7 SP1 x64

**Comment by Snawoot** [comment]
Sorry, it's not supported by recent versions of Golang (1.21 and newer), and hola-proxy is now dependent on Golang 1.22.

Last version which supports Windows 7 is indeed 1.12.1. I suggest you to use it, and if you'll encounter any issues with configuration init, try to add command line option `-user-agent "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36"`

That will match closely behavior of recent versions.
