### ISSUE TITLE
How does this work?

### ISSUE THREAD

**Issue by oddmario** [Snawoot/hola-proxy#12]
Hello,

I like this project and I use it to apply the Hola proxy to all the sites globally since the Chrome extension can apply the proxy per site only. I'm also planning to donate once I can get some crypto.

However, I looked into the source code of this project and I couldn't figure out how does it work. What are the credentials used for, and why are they rotated?

I tried debugging the network requests made by the Hola chrome extension and I could get some proxies through the `zgettunnels` API endpoint of the Hola API. I was able to connect to these proxies directly without specifying any proxy authorization headers, and it has been alive for 3 hours already without rotation - what does this project rotate then?

It'd be appreciated if we get this and the way that this project uses to bypass the Hola bans explained, and I highly appreciate the work you put on this :)

Kind regards.

**Comment by oddmario** [comment]
Also it's worth mentioning that setting the proxy type to `peer` never gave a residential IP address. I tried almost all the countries including the major ones like the USA

**Comment by Snawoot** [comment]
> What are the credentials used for, and why are they rotated?

They are used for proxy auth. They are rotated because they expire after a while. Exact period of expiration is unknown to me, so I've chosen reasonable rotation period which works.

> I tried debugging the network requests made by the Hola chrome extension and I could get some proxies through the zgettunnels API endpoint of the Hola API. I was able to connect to these proxies directly without specifying any proxy authorization headers, and it has been alive for 3 hours already without rotation - what does this project rotate then?

From my observations they omit auth requirement for IP addresses which issued at least one authenticated request. I guess it's done for earlier extensions which couldn't supply auth header for each request. However, it's kind of unreliable.

> Also it's worth mentioning that setting the proxy type to peer never gave a residential IP address. I tried almost all the countries including the major ones like the USA

Can't confirm that. I've just run following commands:

Server startup:

```
user@dt1:~> hola-proxy -proxy-type peer
MAIN    : 2021/02/21 23:50:20 main.go:95: INFO     Constructing fallback DNS upstream...
MAIN    : 2021/02/21 23:50:20 main.go:101: INFO     Initializing configuration provider...
MAIN    : 2021/02/21 23:50:20 main.go:114: INFO     Endpoint: zagent1286.hola.org:22223
MAIN    : 2021/02/21 23:50:20 main.go:115: INFO     Starting proxy server...
PROXY   : 2021/02/21 23:55:17 handler.go:41: INFO     Request: 127.0.0.1:57220 GET http://2ip.ru/
PROXY   : 2021/02/21 23:55:18 handler.go:214: INFO     127.0.0.1:57220 GET http://2ip.ru/ 200 OK
```

Request:

```
user@dt1:~> curl -x 127.0.0.1:8080 2ip.ru
66.27.76.2
```

Clearly, I've got a residential IP address. I don't know why you can't get residential IP address, though.

**Comment by oddmario** [comment]
Thank you so much for your replies.

> Can't confirm that. I've just run following commands:
> 
> Server startup:
> 
> ```
> user@dt1:~> hola-proxy -proxy-type peer
> MAIN    : 2021/02/21 23:50:20 main.go:95: INFO     Constructing fallback DNS upstream...
> MAIN    : 2021/02/21 23:50:20 main.go:101: INFO     Initializing configuration provider...
> MAIN    : 2021/02/21 23:50:20 main.go:114: INFO     Endpoint: zagent1286.hola.org:22223
> MAIN    : 2021/02/21 23:50:20 main.go:115: INFO     Starting proxy server...
> PROXY   : 2021/02/21 23:55:17 handler.go:41: INFO     Request: 127.0.0.1:57220 GET http://2ip.ru/
> PROXY   : 2021/02/21 23:55:18 handler.go:214: INFO     127.0.0.1:57220 GET http://2ip.ru/ 200 OK
> ```
> 
> Request:
> 
> ```
> user@dt1:~> curl -x 127.0.0.1:8080 2ip.ru
> 66.27.76.2
> ```
> 
> Clearly, I've got a residential IP address. I don't know why you can't get residential IP address, though.

It seems we have different builds here, I downloaded the built binary for Windows x64 and it never shows this on startup:
> MAIN    : 2021/02/21 23:50:20 main.go:114: INFO     Endpoint: zagent1286.hola.org:22223

**Comment by Snawoot** [comment]
It's up to server to choose which proxy host (zagentXXXX) will be selected. Usually they are different on each startup.

**Comment by oddmario** [comment]
> It's up to server to choose which proxy host (zagentXXXX) will be selected. Usually they are different on each startup.

Do you get peer IPs on a machine that is connected to a residential internet connection?

**Comment by Snawoot** [comment]
> Do you get peer IPs on a machine that is connected to a residential internet connection?

Both on my local ISP and on VM in DigitalOcean

**Comment by oddmario** [comment]
> > Do you get peer IPs on a machine that is connected to a residential internet connection?
> 
> Both on my local ISP and on VM in DigitalOcean

That's really weird, I am on a cloud server with a datacenter IP and all the proxies that I get with `-proxy-type peer -country us` are DigitalOcean ones.

**Comment by Snawoot** [comment]
Very strange. Then try to grab peer proxy from your residential IP and use host, port and credentials on your VM in datacenter. Maybe it'll help or at least point out somehow what's going on.

**Comment by Snawoot** [comment]
P.S. There is a `-list-proxies` option which allows to grab proxy host, port and creds.

**Comment by oddmario** [comment]
Just got myself a DigitalOcean droplet, tried the peer proxy type and it still gave back a datacenter one. I can't figure out what can the issue be

**Comment by oddmario** [comment]
Tried running the binary file using some residential proxies and couldn't get any valid peer addresses as well
