### ISSUE TITLE
Working around the broken peer flag

### ISSUE THREAD

**Issue by oddmario** [Snawoot/hola-proxy#13]
Hello,

So in my issue #12 I mentioned that the `-proxy-type peer` flag is broken because I never got a residential IP through it.

At first I thought that it might be because I was running the Hola proxy server using a machine with a server IP address. But no, I got on my computer which has a residential IP address and it still gave DigitalOcean proxies even though the proxy type flag was set to give peer ones.

Then I checked your tests at https://github.com/Snawoot/hola-proxy/issues/4#issuecomment-629874771 and https://github.com/Snawoot/hola-proxy/issues/12#issuecomment-782935208

You used https://2ip.ru - So I tried the same and I actually got a residential IP!
To be honest, I thought 2ip.ru was broken because I couldn't trust this haha. However I tried https://icanhazip.com which gave the same residential IP address.

I came back to the APIs I were using before (http://ip-api.com/json and my own IP lookup API on my website) and it gave back the direct DigitalOcean proxy even though it gave a residential one for 2ip.ru and icanhazip.com

The first thing that came into my mind is that it might be giving back the direct proxy on the CloudFlare protected sites (because my own API is Cloudflare protected), but it seems ip-api.com isn't CloudFlare protected.

Came into another site which is https://extreme-ip-lookup.com and it gave back the residential IP address.

I quickly hosted this on my own API, which prints all the request headers:
```php
<?php
var_dump(getallheaders());
?>
```

3 of the headers included IPs.
```
array {
  ["Cf-Connecting-Ip"]=>
  string(15) "138.197.145.194"
  ["X-Forwarded-For"]=>
  string(15) "138.197.145.194"
  ["X-Real-Ip"]=>
  string(15) "108.162.241.248"
}
```

`Cf-Connecting-Ip` and `X-Forwarded-For` are the direct Hola DigitalOcean IPs, and `X-Real-Ip` is the Cloudflare node IP address.

What's next? I predicted that the residential IP isn't applied to the `http://` sites because ip-api.com/json was HTTP (HTTPS requires a premium plan)
But I tried http://icanhazip.com (HTTP this time) and it returned the residential IP address.

Tried https://manytools.org/http-html-text/http-request-headers/ which returned the `X-Forwarded-For` and `X-Real-Ip` as the DigitalOcean IPs too (NOTE: My own browser sends those two headers too with my own residential IP address)

**Summary:** Both of the `X-Forwarded-For` and `X-Real-Ip` headers should be removed from the requests when the proxy type is set as `peer`, or IMHO, its better to remove them anyway regardless the proxy type.

Kind regards.

**Comment by oddmario** [comment]
UPDATE: It seems the headers are sent  by the zagent proxy which I guess makes this harder to solve?

**Comment by oddmario** [comment]
Well, this doesn't seem the issue. I tried running curl in verbose mode and I could see the header `X-Hola-Forbid-Peer: 1` in all the sites that returns the DigitalOcean IP.

**Comment by Snawoot** [comment]
Hi!

> 3 of the headers included IPs.

These headers are added by reverse proxies like CDN (Cloudflare). Use http://httpbin.org/headers to check headers.

> Well, this doesn't seem the issue. I tried running curl in verbose mode and I could see the header X-Hola-Forbid-Peer: 1 in all the sites that returns the DigitalOcean IP.

It seems they decide to redirect traffic via residental proxies or not looking at destination address/domain. Probably their logic can be circumvented with the same trick we use to workaround access via proxies to sites requiring paid subscription (like github.com).

**Comment by oddmario** [comment]
> It seems they decide to redirect traffic via residental proxies or not looking at destination address/domain. Probably their logic can be circumvented with the same trick we use to workaround access via proxies to sites requiring paid subscription (like github.com).

I don't think it will work in this case. I tried accessing the direct IP of ip-api.com and it still returned the direct IP address,

**Comment by oddmario** [comment]
It gets decided by the domain. I tried the direct IP address of 2ip.ru and it added the Hola forbid peer header, while the domain works fine.
Also tried the English version of 2ip.ru (2ip.io) and it added the forbid peer header.
So yeah, its decided through the domain

**Comment by Snawoot** [comment]
Well, technically if we set up domain XXXXX.RU which maps all subdomain queries YYYYY.COM.XXXXX.RU to IP address of YYYYY.COM and make hola-proxy client rewrite requests, then we may have good chances to circumvent it. Problem is it'll require some infrastructure and complex configuration of DNS server. At this moment I can't dedicate that much time to it.

**Comment by oddmario** [comment]
> Well, technically if we set up domain XXXXX.RU which maps all subdomain queries YYYYY.COM.XXXXX.RU to IP address of YYYYY.COM and make hola-proxy client rewrite requests, then we may have good chances to circumvent it. Problem is it'll require some infrastructure and complex configuration of DNS server. At this moment I can't dedicate that much time to it.

Do you mean to get your own .ru domain name? Because it doesn't seem to work with any .ru domain name.

**Comment by Snawoot** [comment]
> Do you mean to get your own .ru domain name? Because it doesn't seem to work with any .ru domain name.
Yes, assuming we can have some domain (not necessarily .RU) which passes for residental IP.

**Comment by oddmario** [comment]
> > Do you mean to get your own .ru domain name? Because it doesn't seem to work with any .ru domain name.
> 
> Yes, assuming we can have some domain (not necessarily .RU) which passes for residental IP.

I think Hola allows only some domains to access the peers network (including netflix.com, hulu.com, and such services), and they included most of the IP lookup domains in their list which to me seems a tricky move from them to be honest.

**Comment by rany2** [comment]
@oddmario Could you confirm the new `-proxy-type pool` and `-proxy-type lum` work for you?

**Comment by oddmario** [comment]
> @oddmario Could you confirm the new `-proxy-type pool` and `-proxy-type lum` work for you?
> 
> Edit: it seems like `-proxy-type peer` will remain broken. I'm not sure what purpose it serves tbf

@rany2 this worked perfectly! However what does the extension use when it comes to residential IPs?

**Comment by rany2** [comment]
@oddmario It seems to be using both luminati and pool. I believe they're just using them both interchangeably because I can't find any difference....

**Comment by oddmario** [comment]
> @oddmario It seems to be using both luminati and pool for residential ips. I believe they're just using them both interchangeably because I can't find any difference....

@rany2 its not what I expected. I thought Hola is an actual P2P VPN like Tuxler VPN for example.
Hola is mysterious in a lot of points

**Comment by aarivex** [comment]
Glad I wasn't the only one experiencing this.

At first I only used `whoer.net` to get the current IP and it gave me the real residential IPs as intended, but other pages such as `browserleaks.com/ip` and `ip-api.com` gave me the IP of the hola server.

The new version works just fine with `lum` and `pool`, but I only get **Altus Communications** as provider and other countries, such as Germany (DE) are not available, as holaproxy throws `CRITICAL Unable to determine proxy endpoint: No tunnels found in API response`.

**Comment by aarivex** [comment]
@rany2 It does. The extension itself pretty much supports every country that is also listed in hola-proxy, including Germany.
`direct` and `peer` also make a difference, because using `direct` as proxy type makes every website show a datacenter IP, whereas using `peer` reflects the problem described above.

Thats why it confuses me that `lum` doesn't yet work with countries such as DE.

**Comment by aarivex** [comment]
> 
> 
> Well, technically if we set up domain XXXXX.RU which maps all subdomain queries YYYYY.COM.XXXXX.RU to IP address of YYYYY.COM and make hola-proxy client rewrite requests, then we may have good chances to circumvent it. Problem is it'll require some infrastructure and complex configuration of DNS server. At this moment I can't dedicate that much time to it.

Would this still work?

I bought Hola Premium since I thought you'd get access to the residential pool with it, since they state that you'll access 7.7M+ IPs worldwide. You'll only get residential IPs with selected hosts. Netflix always got a residential IP, whereas other pages got a datacenter one.

**Comment by aarivex** [comment]
It's also funny how while Hola claims that the free plan doesn't have access to the 7M IP pool, you still get residential IPs on Netflix with the standalone client.

![Hola](https://user-images.githubusercontent.com/18628875/126397720-aece501e-2fe3-42cb-b0b1-b5ca2c0acc01.png)

**Comment by Snawoot** [comment]
@aarivex Noone tried it. I guess you may try following:
1. setup domain which is eligible to be accessed via residental IPs
2. delegate it to something like CoreDNS server with [rewrite plugin](https://coredns.io/plugins/rewrite/), having example.org.yourdomain.tk rewritten to example.org
3. adjust hola-client to add `".yourdomain.tk"` to proxied domain names in CONNECT handler
