### ISSUE TITLE
Research what `-proxy-type peer` does

### ISSUE THREAD

**Issue by rany2** [Snawoot/hola-proxy#19]
For now it doesn't seem to be doing much of anything. Perhaps it should become an alias to either `lum` or `pool`

**Comment by Snawoot** [comment]
Hope users will figure out that themselves

**Comment by rany2** [comment]
Interesting thing is that when the extension uses a 22223 proxy I can't find X-Hola-Forbid-Peer. So perhaps they're doing something extra we're not aware of
