### ISSUE TITLE
Are Hola accounts required now? 

### ISSUE THREAD

**Issue by rany2** [Snawoot/hola-proxy#23]
I keep getting 401 Unauthorized right now. Could someone else could confirm that the same is happening?

**Comment by aarivex** [comment]
No issues at my end. Latest version on Linux (amd64), both **proxy-type** `lum` and `direct` work fine.

![grafik](https://user-images.githubusercontent.com/18628875/110674715-74586f00-81d2-11eb-825f-5f5f69d0ebd1.png)

**Comment by rany2** [comment]
Interesting, hopefully they aren't trying to crack down because I haven't the energy to try to fix anything.

**Comment by Snawoot** [comment]
Also no issues. Hola API may ban IP addresses which abuse them too actively. See #8 for possible workarounds: https://github.com/Snawoot/hola-proxy/issues/8#issuecomment-753367582

**Comment by rany2** [comment]
Closing this. Thanks for the link to #8
