### ISSUE TITLE
Add way of detecting if API blocks you

### ISSUE THREAD

**Issue by rany2** [Snawoot/hola-proxy#24]
```shell
$ curl -X POST --data-raw 'login=1&ver=1.181.350' \
         --user-agent \
         'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.72 Safari/537.36'  \
         https://client.hola.org/client_cgi/background_init?uuid=`uuidgen | tr -d '-'`
{"blocked":true,"permanent":false}
```

could be used to detect if API blocks you. If it does, we might want to add the ability to login using Hola accounts as another workaround besides using a proxy

Edit: would be better than the cryptic: `CRITICAL Unable to determine proxy endpoint: No tunnels found in API response`

**Comment by Snawoot** [comment]
Merged into master code detecting ban in bg_init response. If you'll be "lucky" to experience another ban, please tell if it works for you and I'll make a new release.
