### ISSUE TITLE
Consider using hola source code to develop this

### ISSUE THREAD

**Issue by rany2** [Snawoot/hola-proxy#31]
https://github.com/rany2/libhola_svc/tree/master/out has the holasvc source code which might be useful for this

(no obfuscation)

**Comment by Snawoot** [comment]
Thanks!

**Comment by Snawoot** [comment]
Main concern for this project is availability of Hola API which may be disrupted by state blocking or bans/limits imposed by Hola itself. For this reason fate of this project is uncertain in a long-term perspective, therefore it makes less reasonable to put significant efforts in development of this project.

At this moment project has no clear roadmap. However, with sufficient confirmation that tool serves it's purpose for a number of users, it's feasible to implement a (hosted) censorship-resistant companion service which allows hola-proxy client application instances to donate received proxy credentials to each other, overcoming disruptions w/o huge recurring costs to operator of such service.

**Comment by rany2** [comment]
https://github.com/rany2/libhola_svc/blob/6b50155b0fa0ef4fa365b7faaec908020493ba8a/out/svc/vpn/peer/conn_mgr.js#L46-L57 seems to show techniques to circumvent censorship. We could connect to those via Tor which is pretty censorship resilient to initialize the proxy credentials.

```
$ wget -qO cloud_failover.conf 'https://www.dropbox.com/s/jemizcvpmf2qb9v/cloud_failover.conf?dl=1'
$ node 
Welcome to Node.js v15.11.0.
Type ".help" for more information.
> fs.readFile('cloud_failover.conf', 'utf8' , (err, res) => { res = res.substr(res.length-3)+res.substr(0, res.length-3); if (res.length%4) res += '='.repeat(4-res.length%4); res = Buffer.from(res, 'base64').toString(); console.log(res)});
undefined
> {"agents":[{"name":"zagent674","ip":"192.241.230.65","port":22224},{"name":"zagent814","ip":"192.241.230.164","port":22224},{"name":"zagent515","ip":"45.76.227.240","port":22224},{"name":"zagent1273","ip":"161.35.96.224","port":22224},{"name":"zagent652","ip":"161.35.50.91","port":22224}],"updated_ts":1615658408455,"ttl_ms":28800000}

>

$ torsocks curl -x https://zagent674.hola.org:22224 -X POST --data-raw 'login=1&ver=1.181.350'          --user-agent          'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.72 Safari/537.36'           https://client.hola.org/client_cgi/background_init?uuid=`uuidgen | tr -d '-'`
{"ver":"1.181.829","country":"US","key":140009840}
```

This could be the best way to circumvent censorship and get proxy credentials

**Comment by rany2** [comment]
What do you think?

**Comment by Snawoot** [comment]
Looks like requests via these failover proxies are whitelisted without regard of requested IP banned. At least it resolves issue with IP bans. I think it's worth implementing as a fallback for usual credential retrieval flow.
