### ISSUE TITLE
It looks like proxy-type is useless as all requests come from hola servers anyway

### ISSUE THREAD

**Issue by s04lg934jkg** [Snawoot/hola-proxy#37]
Regardless of proxy-type or port used for connection, all http requests are sent from hola servers, not from residential IPs (when I use peer or lum or any other proxy types)

**Comment by Snawoot** [comment]
Can't confirm that. I'm running hola-proxy like this: `hola-proxy -proxy-type lum` (US).

I get this IP address:

```
> curl -x 127.0.0.1:8080 http://2ip.ru
154.17.57.152
```

Probably you're trying to use residential IPs through a country where they are not present.
