### ISSUE TITLE
flag "peer" does not work

### ISSUE THREAD

**Issue by cyrillpetroff** [Snawoot/hola-proxy#4]
When I trying check my ip in some services (like ifconfig.io), and set flag "peer", I see, that my connection still going by the hola node (direct), not by the peer...

**Comment by Snawoot** [comment]
Some regions without actual peer nodes forward requests on peer port directly. So please check "peer" mode with `-country us` for example.

**Comment by mirkokg** [comment]
I can confirm that peer mode does not work at all. I tried many major countries. I also tried Hola Chrome extension just for comparison, and it worked with it, but with hola-proxy I am always getting digitalocean IPs.

**Comment by Snawoot** [comment]
Can't confirm that. I've added endpoint output to log and I see:

```
user@hp:~/src/hola-proxy> go run . -country us -proxy-type peer
MAIN    : 2020/05/18 01:59:36 main.go:95: INFO     Constructing fallback DNS upstream...
MAIN    : 2020/05/18 01:59:36 main.go:101: INFO     Initializing configuration provider...
MAIN    : 2020/05/18 01:59:37 main.go:114: INFO     Endpoint: zagent586.hola.org:22223
MAIN    : 2020/05/18 01:59:37 main.go:115: INFO     Starting proxy server...
PROXY   : 2020/05/18 02:00:12 handler.go:41: INFO     Request: 127.0.0.1:38996 GET http://2ip.ru/
PROXY   : 2020/05/18 02:00:14 handler.go:214: INFO     127.0.0.1:38996 GET http://2ip.ru/ 200 OK
```

In another terminal session:

```
user@hp:~/src/hola-proxy> host zagent586.hola.org
zagent586.hola.org has address 67.205.129.168
user@hp:~/src/hola-proxy> curl --proxy localhost:8080 2ip.ru
75.139.150.25
```

Obviously, it's not a direct proxy and exit IP belongs to consumer ISP network.

**Comment by mirkokg** [comment]
Tried to do the same now, I am getting:

hola-proxy -country us -proxy-type peer
MAIN    : 2020/05/18 01:06:40 main.go:95: INFO     Constructing fallback DNS upstream...
MAIN    : 2020/05/18 01:06:40 main.go:101: INFO     Initializing configuration provider...
MAIN    : 2020/05/18 01:06:43 main.go:110: CRITICAL Unable to determine proxy endpoint: No tunnels found in API response

Will try again later, strange.

**Comment by janisblaus** [comment]
Nice work, it was so easy to install this package. 

Can confirm that -peer does not work tho. Exists to digitalocean vps.

**Comment by mirkokg** [comment]
@janisblaus you can use peers only for listed countries, not all countries unforntally. Use -list-countries to see which countries you can use. In my experience it works for those countries.
