### ISSUE TITLE
 handler.go:49: ERROR    Can't satisfy CONNECT request: dial tcp : i/o timeout

### ISSUE THREAD

**Issue by eliaweiss** [Snawoot/hola-proxy#46]
After sometime of using the proxy it stops working with the errors:

 handler.go:49: ERROR    Can't satisfy CONNECT request: dial tcp : i/o timeout
 handler.go:49: ERROR    Can't satisfy CONNECT request: dial tcp : operation was canceled

if I reset the process it almost always solve the problem

**Comment by Snawoot** [comment]
Looks like server itself went down.

**Comment by Snawoot** [comment]
hola-proxy connects to servers which belong to Hola.

Either one (that you use) of them stopped working, or they set up packet filter to block requests from your IP due to high amount of traffic comming from you (happens from time to time).

**Comment by Snawoot** [comment]
> If I restart the hola-proxy, does it change the server?

Yes

> Is there a way to change the server without a restart?

No, at this moment.
