### ISSUE TITLE
Support for Socks proxy?

### ISSUE THREAD

**Issue by cs16lover** [Snawoot/hola-proxy#47]
Hello @Snawoot,

First of all thank you for such a great project.

Is it possible to add Socks support for using hola-proxy? 

Thanks

**Comment by Snawoot** [comment]
Hello!

Do you mean option to act like a SOCKS proxy instead of HTTP one? It's possible, but I see no reason why. Practically every software capable to work with proxies works with HTTP proxy in the first place.

**Comment by cs16lover** [comment]
> Hello!
> 
> Do you mean option to act like a SOCKS proxy instead of HTTP one? 

Yes, exactly. 

> It's possible, but I see no reason why. Practically every software capable to work with proxies works with HTTP proxy in the first place.

Some softwares communicates using custom TCP (not HTTP) protocols. So I tried and they didn't worked on HTTP proxy.

**Comment by Snawoot** [comment]
Custom TCP communication still possible if application wraps connection in HTTP CONNECT method. That's practically how HTTPS works over proxy. So which software we're talking about?

**Comment by cs16lover** [comment]
> Custom TCP communication still possible if application wraps connection in HTTP CONNECT method. That's practically how HTTPS works over proxy. So which software we're talking about?

WhatsApp and Telegram

**Comment by Snawoot** [comment]
Both of them work via HTTP proxies just fine.
