### ISSUE TITLE
Server Functionality Confusion

### ISSUE THREAD

**Issue by SalvadorSTM** [Snawoot/hola-proxy#48]
I've setup hola proxy on a server and wanted to connect to it from another machine so I could use the machine I installed it on as a proxy server.
Is this project meant to do that?
After checking that the service is running, how do I connect to the proxy server from another computer?

**Comment by aarivex** [comment]
You're completely wrong here.

This project is not a bare proxy server. If you wish to use a server of yours as a proxy server, you can create a SSH tunnel.
More info [here](https://ma.ttias.be/socks-proxy-linux-ssh-bypass-content-filters/).

**Comment by SalvadorSTM** [comment]
Excellent. Thank you for the help.

**Comment by Snawoot** [comment]
@SalvadorSTM Probably [dumbproxy](https://github.com/Snawoot/dumbproxy) is what you're looking for.
