### ISSUE TITLE
HTTP fetch error: context canceled

### ISSUE THREAD

**Issue by cyrillpetroff** [Snawoot/hola-proxy#49]
Hi there.  I get this error, sites do not open...

> C:\Users\user\Downloads>hola-proxy -proxy-type pool -country br
MAIN    : 2021/07/02 03:23:28 main.go:147: INFO     hola-proxy client version v1.5.1 is starting...
MAIN    : 2021/07/02 03:23:28 main.go:148: INFO     Constructing fallback DNS upstream...
MAIN    : 2021/07/02 03:23:28 main.go:155: INFO     Initializing configuration provider...
MAIN    : 2021/07/02 03:23:29 main.go:168: INFO     Endpoint: https://zagent909.hola.org:22225
MAIN    : 2021/07/02 03:23:29 main.go:169: INFO     Starting proxy server...
MAIN    : 2021/07/02 03:23:29 main.go:171: INFO     Init complete.
PROXY   : 2021/07/02 03:24:57 handler.go:104: INFO     Request: 127.0.0.1:57929 HTTP/1.1 GET http://detectportal.firefox.com/success.txt
PROXY   : 2021/07/02 03:24:58 handler.go:104: INFO     Request: 127.0.0.1:57931 HTTP/1.1 GET http://2ip.ru/
PROXY   : 2021/07/02 03:25:02 handler.go:90: ERROR    HTTP fetch error: context canceled
PROXY   : 2021/07/02 03:25:02 handler.go:104: INFO     Request: 127.0.0.1:57933 HTTP/1.1 GET http://detectportal.firefox.com/success.txt
PROXY   : 2021/07/02 03:25:07 handler.go:90: ERROR    HTTP fetch error: context canceled
PROXY   : 2021/07/02 03:25:07 handler.go:104: INFO     Request: 127.0.0.1:57935 HTTP/1.1 GET http://detectportal.firefox.com/success.txt
PROXY   : 2021/07/02 03:25:12 handler.go:90: ERROR    HTTP fetch error: context canceled
PROXY   : 2021/07/02 03:25:12 handler.go:104: INFO     Request: 127.0.0.1:57937 HTTP/1.1 GET http://detectportal.firefox.com/success.txt
PROXY   : 2021/07/02 03:25:17 handler.go:90: ERROR    HTTP fetch error: context canceled
PROXY   : 2021/07/02 03:25:17 handler.go:104: INFO     Request: 127.0.0.1:57939 HTTP/1.1 GET http://detectportal.firefox.com/success.txt
PROXY   : 2021/07/02 03:25:19 handler.go:90: ERROR    HTTP fetch error: proxyconnect tcp: dial tcp 191.96.70.220:22225: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
PROXY   : 2021/07/02 03:25:19 handler.go:104: INFO     Request: 127.0.0.1:57931 HTTP/1.1 GET http://2ip.ru/favicon.ico
PROXY   : 2021/07/02 03:25:22 handler.go:90: ERROR    HTTP fetch error: context canceled
PROXY   : 2021/07/02 03:25:22 handler.go:104: INFO     Request: 127.0.0.1:57943 HTTP/1.1 GET http://detectportal.firefox.com/success.txt
PROXY   : 2021/07/02 03:25:24 handler.go:104: INFO     Request: 127.0.0.1:57945 HTTP/1.1 CONNECT //aus5.mozilla.org:443
PROXY   : 2021/07/02 03:25:27 handler.go:90: ERROR    HTTP fetch error: context canceled
PROXY   : 2021/07/02 03:25:40 handler.go:90: ERROR    HTTP fetch error: proxyconnect tcp: dial tcp 191.96.70.220:22225: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
PROXY   : 2021/07/02 03:25:40 handler.go:104: INFO     Request: 127.0.0.1:57931 HTTP/1.1 GET http://2ip.ru/favicon.ico
PROXY   : 2021/07/02 03:25:44 handler.go:49: ERROR    Can't satisfy CONNECT request: dial tcp 191.96.70.220:22225: operation was canceled
PROXY   : 2021/07/02 03:25:44 handler.go:104: INFO     Request: 127.0.0.1:55795 HTTP/1.1 GET http://ciscobinary.openh264.org/openh264-win32-0410d336bb748149a4f560eb6108090f078254b1.zip
PROXY   : 2021/07/02 03:26:01 handler.go:90: ERROR    HTTP fetch error: proxyconnect tcp: dial tcp 191.96.70.220:22225: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
PROXY   : 2021/07/02 03:26:03 handler.go:90: ERROR    HTTP fetch error: context canceled
PROXY   : 2021/07/02 03:26:03 handler.go:104: INFO     Request: 127.0.0.1:55805 HTTP/1.1 GET http://ciscobinary.openh264.org/openh264-win32-0410d336bb748149a4f560eb6108090f078254b1.zip
PROXY   : 2021/07/02 03:26:24 handler.go:90: ERROR    HTTP fetch error: proxyconnect tcp: dial tcp 191.96.70.220:22225: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
PROXY   : 2021/07/02 03:26:24 handler.go:104: INFO     Request: 127.0.0.1:63778 HTTP/1.1 CONNECT //redirector.gvt1.com:443
PROXY   : 2021/07/02 03:26:45 handler.go:49: ERROR    Can't satisfy CONNECT request: dial tcp 191.96.70.220:22225: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.

**Comment by Snawoot** [comment]
Hi!

I'm not sure what exactly all proxy types are doing: #19 

However, we know that proxy types `direct` are known to be datacenter IPs and `lum` are residential IPs. Try either of these two. Perhaps I should remove other types at all because they are no use for user.
