### ISSUE TITLE
Feature suggestion : rotate proxy per given period or per x requests

### ISSUE THREAD

**Issue by thit-ga-luoc** [Snawoot/hola-proxy#5]
Hi,
I do web scraping regularly. Most system I've been worked with blocks an IP after a number of requests or after excessive requests in a given period of time. I think it would be nicer if the client can rotate proxy per given period or per x requests.
What do you think?

**Comment by Snawoot** [comment]
Hi!

If you are doing web-scrapping you may consider following options:

* Extract proxy list and access credentials (`-list-proxies` option) and use them programmatically according to policy of your choice.
* Use predecessor of this application, [hola-proxy-list](https://github.com/Snawoot/hola-proxy-list). It is capable to generate a config file for `haproxy` daemon, using your config template. That config template can be set to use some balancing policy like round-robin. Also haproxy is quite flexible, versatile and can do many other things.
