### ISSUE TITLE
How to know the password associated with uuid

### ISSUE THREAD

**Issue by Jeffade1** [Snawoot/hola-proxy#52]
Hi @Snawoot and everyone.
When we use hola-proxy to get a list of proxies, it generates automatically a login (user-uuid-xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx) and a password (xxxxxxxxxxxx) and show them.
When we use hola browser extension or desktop app, it's only possible to see the login uuid.
How and where can we get the password associated with the login from hola?
Thanks in advance👍

**Comment by Snawoot** [comment]
Hi!

Not sure about desktop app, but for browser extension password is returned as "agent_key" in request to `https://client.hola.org/client_cgi/zgettunnels`. Relevant source code can be found here: https://github.com/Snawoot/hola-proxy/blob/7d891ac61356f274cf42bcb39d4606fc76d06968/holaapi.go#L217-L254

Probably you can reproduce such request with the uuid you need.
