### ISSUE TITLE
Possibility to use on headless server/router?

### ISSUE THREAD

**Issue by tornadox** [Snawoot/hola-proxy#53]
Hi! Thanks for this amazing app. Is it possible to use the proxy on a headless Linux box or router to connect to it afterwards via IP and PORT?

**Comment by Snawoot** [comment]
Hi! Thanks!

Yes, it's possible. See [this wiki page](https://github.com/Snawoot/hola-proxy/wiki/Autostart-on-Linux) for example of autostart on Linux. Also you'll need to add `-listen 0.0.0.0:8080` option to OPTIONS in order to enable connectivity from other hosts.

**Comment by tornadox** [comment]
It's saying this _flag provided but not defined: -listen_

**Comment by tornadox** [comment]
![image](https://user-images.githubusercontent.com/1788423/128638034-3ab14129-7d25-47b4-b47c-359d2afff74f.png)
I see thanks, I've tried this option and it doesn't seem to work. As well added all of the containers and in logs, I see no connectivity. The docker host is a clean Debian 10 host x86.  Any ideas on how I can troubleshoot this?

**Comment by tornadox** [comment]
It seems to work on an arm box, so will check the firewall settings.

**Comment by tornadox** [comment]
When running directly with the bind command all of them work fine, but with the docker container, I don't get connectivity.  =(

**Comment by Snawoot** [comment]
@tornadox what docker command do you use?

**Comment by tornadox** [comment]
sudo docker run -d \
>     --security-opt no-new-privileges \
>     -p 127.0.0.1:8080:8080 \
>     --restart unless-stopped \
>     --name hola-proxy \
>     yarmak/hola-proxy -country de

**Comment by Snawoot** [comment]
In this case use `-p 8080:8080` instead of `-p 127.0.0.1:8080:8080`

**Comment by tornadox** [comment]
thank you! It worked!

**Comment by tornadox** [comment]
I know this one is not related to windscribe proxy, but once started I get this

```
MAIN    : 2021/08/08 16:52:22 main.go:192: CRITICAL Cold init failed: bad http status: 400 Bad Request, headers: http.Header{"Access-Control-Allow-Headers":[]string{"Origin, X-Requested-With, Content-Type, Accept"}, "Access-Control-Allow-Origin":[]string{"*"}, "Cache-Control":[]string{"no-cache, no-store, max-age=0, must-revalidate"}, "Cf-Cache-Status":[]string{"DYNAMIC"}, "Cf-Railgun":[]string{"9a8ebb9c48 1.54 0.010990 0032 57da"}, "Cf-Ray":[]string{"67ba413878ea3d71-KBP"}, "Connection":[]string{"keep-alive"}, "Content-Type":[]string{"text/html; charset=UTF-8"}, "Date":[]string{"Sun, 08 Aug 2021 16:52:22 GMT"}, "Expect-Ct":[]string{"max-age=604800, report-uri=\"https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct\""}, "Server":[]string{"cloudflare"}, "Strict-Transport-Security":[]string{"max-age=16000000; includeSubDomains; preload;"}}

MAIN    : 2021/08/08 16:52:25 main.go:122: INFO     windscribe-proxy client version v1.0.2 is starting...

MAIN    : 2021/08/08 16:52:25 main.go:189: WARNING  Failed to load client state: open /state/wndstate.json: no such file or directory. Performing cold init...
```
