### ISSUE TITLE
issue with proxychains

### ISSUE THREAD

**Issue by fenopa** [Snawoot/hola-proxy#56]
when I want to use it with proxychains, getting "can't satisfy CONNECT request: bad responce from upstream proxy server: 403 bad port" error with HTTP links, but works fine with HTTPS links.

basically same issue like this: https://github.com/rofl0r/proxychains-ng/issues/263
also this: https://github.com/openbullet/OpenBullet2/issues/333

I see you rejected socks support here: https://github.com/Snawoot/hola-proxy/issues/47
but wondering if socks support would solve this issue?

**Comment by fenopa** [comment]
well, no issue with windscribe-proxy and proxychains. is it because hola only allows https traffic? that's weird.

**Comment by Snawoot** [comment]
Hello,

Hola allows CONNECT method only for HTTPS. And also they allow plain HTTP requests with absolute URI (it's how it normally HTTP goes through proxy). CONNECT to any port other than 443 is not allowed AFAIK.

But for chaining you need to have proxy just for TCP connection to another proxy, hence CONNECT method is used for chaining.

The only way of chaining possible now (and supported by `hola-proxy` natively) is to access Hola proxies via some another proxy, not vice versa. See `-proxy` option in command line arguments.

**Comment by fenopa** [comment]
Hi, thank you for your reply, appreciate it. But I still don't understand why your other tool windscribe-proxy does not have an issue?

I mean, I do this with windscribe-proxy:
proxychains4 curl icanhazip.com
and all fine

I do same with hola-proxy and it only works with https://icanhazip.com

**Comment by Snawoot** [comment]
Because windscribe-proxy uses windscribe servers which have no such restrictions as hola servers.

**Comment by fenopa** [comment]
Right, all clear, I felt stupid now (had read your first sentence as "Hola-proxy allows CONNECT method only for HTTPS", but you were talking about limitation of the service, sorry for taking your time and thanks for all explanations.

**Comment by Snawoot** [comment]
No problem!

**Comment by nyuszika7h** [comment]
For anyone interested, pproxy with this patch and the `httponly://` scheme can tunnel both HTTP and HTTPS connections to hola-proxy (although it's a hacky solution hardcoding port 443): https://github.com/nyuszika7h/python-proxy/commit/23a1854e84a6a0a21ab0e92adc3eebafc86e3ad3
