### ISSUE TITLE
Can't Get residential ip, residential ip still working?

### ISSUE THREAD

**Issue by raddup** [Snawoot/hola-proxy#58]
Tried to investigate the ip routed from hola with -proxy-type lum and i don't get residential ip

my website for investigation is https://ipx.ac/
on tuxler vpn i get only residential ip, why is not working i am doing something wrong?

**Comment by raddup** [comment]
example

curl -x 127.0.0.1:8080 api.ipify.org
64.79.252.6

**Comment by Snawoot** [comment]
Their server rules are changing often and now they redirect requests to datacenter IPs sometimes. At this moment I have no way to do something with it and residential support is not primary objective for this project.
