### ISSUE TITLE
CRITICAL Configuration bootstrap failed

### ISSUE THREAD

**Issue by govnotest** [Snawoot/hola-proxy#6]
when I start the proxy, I get an error:
            
MAIN    : 2020/06/12 19:16:18 main.go:95: INFO     Constructing fallback DNS upstream...
MAIN    : 2020/06/12 19:16:18 main.go:101: INFO     Initializing configuration provider...
CRED    : 2020/06/12 19:16:48 credservice.go:34: CRITICAL Configuration bootstrap failed: Post "https://client.hola.org/client_cgi/background_init?uuid=c8452095d2794ab08badd98ce55835b9": context deadline exceeded
MAIN    : 2020/06/12 19:16:48 main.go:104: CRITICAL Unable to instantiate credential service: Post "https://client.hola.org/client_cgi/background_init?uuid=c8452095d2794ab08badd98ce55835b9": context deadline exceeded
Tell me, how can I fix this?

**Comment by Snawoot** [comment]
Hi,

It means request timeout expired. Please check that domain `client.hola.org` is available from your machine via HTTPS.
