### ISSUE TITLE
Could not open CONNECT tunnel with proxy

### ISSUE THREAD

**Issue by aloysius-tim** [Snawoot/hola-proxy#62]
Hey there,
Would love to test your project, but looks like it's not working anymore today
Or maybe I just use it the wrong way...
All my requests look like:
`Could not open CONNECT tunnel with proxy zagent1495.hola.org:22222 [{'status': 403, 'reason': b'Auth Failed'}]`
or 
`Connection was refused by other side: 61: Connection refused.`

Thanks,
Tim

**Comment by Snawoot** [comment]
Hello,

I don't experience such problems, not sure why they've banned you.
