### ISSUE TITLE
-proxy-type lum gives datacenter IP

### ISSUE THREAD

**Issue by szalony9szymek** [Snawoot/hola-proxy#63]

**Comment by szalony9szymek** [comment]
I have tried different countries, all get datacenter IP's, some from the wrong countries even

**Comment by TheRegressor** [comment]
same with me, getting digitalocean and vultr

**Comment by weselow** [comment]
Faced the same issue... are there any solutions?

**Comment by Vangelis66** [comment]
Possibly duplicate of #58 😜 ...
