### ISSUE TITLE
CRITICAL Unable to determine proxy endpoint: No tunnels found in API response

### ISSUE THREAD

**Issue by Paikan** [Snawoot/hola-proxy#8]
First, thanks for this very useful project.

I have been using hola-proxy with a lot of success for the last few weeks but it has stopped working 2 days ago with the following error

```
CRITICAL Unable to determine proxy endpoint: No tunnels found in API response
```

I think the IP I was running hola-proxy from has been blacklisted.

I have tried to run it from another VM. It worked perfectly for something like 20 hours and the IP was blacklisted leading to the same error.

Are you aware of new policy on the hola side? Are you aware of any workaround?

**Comment by tia3** [comment]
I just installed to a brand ne centos8, issue is similar.

`[root@host hola-proxy]# ~/go/bin/hola-proxy -verbosity 0
MAIN    : 2021/01/01 18:37:08 main.go:95: INFO     Constructing fallback DNS upstream...
MAIN    : 2021/01/01 18:37:08 main.go:101: INFO     Initializing configuration provider...
MAIN    : 2021/01/01 18:37:09 main.go:110: CRITICAL Unable to determine proxy endpoint: No tunnels found in API response
`

Think so there was a change on Hola's side.

**Comment by Snawoot** [comment]
@Paikan 

There were always some usage limits for IP address from Hola side, but I'm not aware about exact values of these limits.

If it's issue for you, try using hola-proxy itself or another proxy to make hola-proxy fetch credentials from another IP address.

hola-proxy respects HTTP_PROXY and HTTPS_PROXY environment variables (https://golang.org/pkg/net/http/#ProxyFromEnvironment), so internal http client responsible for retrieval of credentials can use another proxy to jumpstart hola-proxy instance.

**Comment by tia3** [comment]
Dear @Snawoot 

Do you have any idea why I got the same error  to the first credential fetch? I have a dedicated server IP in Deutschland, and it was not used earlier to fetch hola credentias.

**Comment by Snawoot** [comment]
@tia3 I have only guess. It's very likely German hosters are very popular in this field and ones like Hetzner are banned "a priori".

However, I've just tested it on my VM in the US (DigitalOcean, NYC1) and it works flawlessly.

**Comment by rany2** [comment]
Are those permanent blocks or do they take some time to expire?

**Comment by Snawoot** [comment]
Can't say for sure. I guess it's temporary.

Regarding limits, I don't know what kind of requests is exactly limited. Maybe it's worth to try less frequent credential rotation interval. I didn't hit such limit too often to make any adjustments.

**Comment by rany2** [comment]
Well I was using 5 hola-proxies in parallel so that probably made the banning of my IP more inevitable. I wasn't aware that this would be my fate...

**Comment by rany2** [comment]
I got unbanned after 12 hours. Just in case someone else is interested to know

**Comment by beshoo** [comment]
> @Paikan
> 
> There always were some usage limits for IP address from Hola side, but I'm not aware about exact values of these limits.
> 
> If it's issue for you, try using hola-proxy itself or another proxy to make hola-proxy fetch credentials from another IP address.
> 
> hola-proxy respects HTTP_PROXY and HTTPS_PROXY environment variables (https://golang.org/pkg/net/http/#ProxyFromEnvironment), so internal http client responsible for retrieval of credentials can use another proxy to jumpstart hola-proxy instance.

Hello,
Do you mean If hola will block server, it will block the Ip address who ask for the credentials? not the Ip who is using the proxy?
This is my use case.
I want to fetch a google Maps, and I need proxies. a lot of.
So your idea is following start Hola command line "List-proxy" by using HTTPS_PROXY which is another proxy- maybe Opra proxy..
If hola will block- they will block the Opra proxy? even if am using the hola proxy from my Linux box... and they will not block my IP address ?
