### ISSUE TITLE
Certificate error for RU

### ISSUE THREAD

**Issue by bodhisatya86** [Snawoot/hola-proxy#95]
When trying to connect to Russia and use it as a proxy, i get the following issue:
PROXY   : 2023/08/24 14:29:52 handler.go:49: ERROR    Can't satisfy CONNECT request: x509: certificate is valid for *.hola-vpn.com, hola-vpn.com, not zagent101.hola.org
Other countries seem to be fine though. I was just wondering if anyone else experienced this issue and if you can provide a fix for it.

**Comment by Snawoot** [comment]
Hello!

This issue is duplicate with #88 

Please try to add command line option `-hide-SNI=false`
