### ISSUE TITLE
hola-proxy completely broken!

### ISSUE THREAD

**Issue by Vangelis66** [Snawoot/hola-proxy#97]
I'm using latest [v1.10.0](https://github.com/Snawoot/hola-proxy/releases/tag/v1.10.0) on a **32-bit** Windows laptop; thus, the binary in use is `hola-proxy.windows-386.exe` 😉 ...

`hola-proxy` was working OK probably two weeks ago (when I last used it), but now: 
1. The app launches and `init` is **successfully complete** (below, when connecting to an **AU** hola node):
```console
MAIN    : 2023/09/06 03:17:27 main.go:192: WARNING  Detected latest extension version: "1.214.740". Pass -ext-ver parameter to skip resolve and speedup startup
MAIN    : 2023/09/06 03:17:27 main.go:200: INFO     hola-proxy client version v1.10.0 is starting...
MAIN    : 2023/09/06 03:17:27 main.go:201: INFO     Constructing fallback DNS upstream...
MAIN    : 2023/09/06 03:17:27 main.go:208: INFO     Initializing configuration provider...
MAIN    : 2023/09/06 03:17:28 main.go:222: INFO     Endpoint: https://zagent2391.hola.org:22225
MAIN    : 2023/09/06 03:17:28 main.go:223: INFO     Starting proxy server...
MAIN    : 2023/09/06 03:17:28 main.go:225: INFO     Init complete.
```
2. Any attempt to use the chosen hola node receives a `403 Auth Failed` denial 😢 : 
```console
PROXY   : 2023/09/06 03:18:19 handler.go:104: INFO     Request: 127.0.0.1:6436 HTTP/1.0 CONNECT //tubitv.com:443
PROXY   : 2023/09/06 03:18:21 handler.go:49: ERROR    Can't satisfy CONNECT request: bad response from upstream proxy server: 403 Auth Failed
```
The **choice of country is irrelevant**, all hola nodes refuse to service the web requests :angry: ; on the CWS, 

https://chrome.google.com/webstore/detail/hola-vpn-the-website-unbl/gkojfkhlekighikafcpjkiklfbnlmeio

it's apparent their extension got updated yesterday (2023-09-05) to `v1.214.740`, so with that Hola must've changed something in **their authentication scheme**, thus rendering the app useless 😡 ...

And another request/favour 😜 : I've got at least two older laptops here running **Windows NT 6.0 and 6.1**; the latest version of go, `1.21`, supports only Win10+; would it be hard for you to keep supporting "legacy" Win OSes by additionally providing **go<=1.20**-compiled `hola-proxy` win-binaries?

Thanks a lot for all that you do 👍 (and if your true location is indeed the one stated in your GH profile, I do hope you're safe and well 💌 😄 ) ...

Greetings.

**Comment by Snawoot** [comment]
Thanks for reporting that! Fixed in [v1.11.0](https://github.com/Snawoot/hola-proxy/releases/tag/v1.11.0). Windows releases will be built with Go 1.20 for a while.

**Comment by Snawoot** [comment]
@chromer030 I can't reproduce it. I'm writting this reply to you through hola-proxy right now.

**Comment by Vangelis66** [comment]
... As of this very moment, I'm not able to reproduce; I successfully connected to a `hola` **US node**, 

`hp.exe -dont-use-trial -country us`

 and then configured `yt-dlp` to use that; no issues encountered: 

`yt-dlp --ies youtube --proxy "http://localhost:8080" -F "7LBYrDx_784"`

`hola-proxy` window:
```console
MAIN    : 2023/10/04 17:14:52 main.go:192: WARNING  Detected latest extension version: "1.215.903". Pass -ext-ver parameter to skip resolve and speedup startup
MAIN    : 2023/10/04 17:14:52 main.go:200: INFO     hola-proxy client version v1.11.0 is starting...
MAIN    : 2023/10/04 17:14:52 main.go:201: INFO     Constructing fallback DNS upstream...
MAIN    : 2023/10/04 17:14:52 main.go:208: INFO     Initializing configuration provider...
MAIN    : 2023/10/04 17:14:53 main.go:222: INFO     Endpoint: https://zagent2449.hola.org:22222
MAIN    : 2023/10/04 17:14:53 main.go:223: INFO     Starting proxy server...
MAIN    : 2023/10/04 17:14:53 main.go:225: INFO     Init complete.
PROXY   : 2023/10/04 17:19:34 handler.go:104: INFO     Request: 127.0.0.1:4880 HTTP/1.0 CONNECT //www.youtube.com:443
PROXY   : 2023/10/04 17:19:40 handler.go:104: INFO     Request: 127.0.0.1:4885 HTTP/1.0 CONNECT //www.google.com:443
PROXY   : 2023/10/04 17:19:45 handler.go:104: INFO     Request: 127.0.0.1:4890 HTTP/1.0 CONNECT //www.youtube.com:443
PROXY   : 2023/10/04 17:19:50 handler.go:104: INFO     Request: 127.0.0.1:4896 HTTP/1.0 CONNECT //www.youtube.com:443
PROXY   : 2023/10/04 17:19:55 handler.go:104: INFO     Request: 127.0.0.1:4902 HTTP/1.0 CONNECT //www.youtube.com:443
PROXY   : 2023/10/04 17:20:00 handler.go:104: INFO     Request: 127.0.0.1:4907 HTTP/1.0 CONNECT //www.youtube.com:443
PROXY   : 2023/10/04 17:20:07 handler.go:104: INFO     Request: 127.0.0.1:4912 HTTP/1.0 CONNECT //www.youtube.com:443
PROXY   : 2023/10/04 17:20:13 handler.go:104: INFO     Request: 127.0.0.1:4917 HTTP/1.0 CONNECT //manifest.googlevideo.com:443
PROXY   : 2023/10/04 17:20:17 handler.go:104: INFO     Request: 127.0.0.1:4922 HTTP/1.0 CONNECT //www.youtube.com:443
```
`yt-dlp` window:
```console
[youtube+AGB+NSIG] Extracting URL: 7LBYrDx_784
[youtube+AGB+NSIG] 7LBYrDx_784: Downloading webpage
WARNING: [youtube+AGB+NSIG] Unable to download webpage: HTTP Error 429: Too Many Requests
[youtube+AGB+NSIG] 7LBYrDx_784: Downloading ios player API JSON
[youtube+AGB+NSIG] 7LBYrDx_784: Downloading android player API JSON
[youtube+AGB+NSIG] 7LBYrDx_784: Downloading iframe API JS
[youtube+AGB+NSIG] 7LBYrDx_784: Downloading player e95f6cb1
[youtube+AGB+NSIG] 7LBYrDx_784: Downloading web player API JSON
[youtube+AGB+NSIG] 7LBYrDx_784: Downloading m3u8 information
WARNING: [youtube+AGB+NSIG] Failed to download m3u8 information: HTTP Error 429: Too Many Requests
[youtube+AGB+NSIG] 7LBYrDx_784: Downloading initial data API JSON
[info] Available formats for 7LBYrDx_784:
ID  EXT   RESOLUTION FPS CH |   FILESIZE  TBR PROTO | VCODEC         VBR ACODEC     ABR ASR MORE INFO
--------------------------------------------------------------------------------------------------------------
sb2 mhtml 48x27        1    |                 mhtml | images             storyboard
sb1 mhtml 45x45        1    |                 mhtml | images             storyboard
sb0 mhtml 91x90        1    |                 mhtml | images             storyboard
139 m4a   audio only      2 |  765.50KiB  49k https | audio only         mp4a.40.5   49k 22k low, m4a_dash
249 webm  audio only      2 |  897.81KiB  57k https | audio only         opus     57k 48k low, webm_dash
250 webm  audio only      2 |    1.17MiB  76k https | audio only         opus     76k 48k low, webm_dash
140 m4a   audio only      2 |    1.98MiB 130k https | audio only         mp4a.40.2  130k 44k medium, m4a_dash
251 webm  audio only      2 |    2.31MiB 151k https | audio only         opus    151k 48k medium, webm_dash
17  3gp   176x144      6  1 |  680.57KiB  43k https | mp4v.20.3          mp4a.40.2       22k 144p
394 mp4   146x144     25    |  332.29KiB  21k https | av01.0.00M.08  21k video only          144p, mp4_dash
160 mp4   146x144     25    |  151.79KiB  10k https | avc1.4D400B    10k video only          144p, mp4_dash
278 webm  146x144     25    |  330.81KiB  21k https | vp09.00.11.08  21k video only          144p, webm_dash
395 mp4   244x240     25    |  468.01KiB  30k https | av01.0.00M.08  30k video only          240p, mp4_dash
133 mp4   244x240     25    |  209.02KiB  13k https | avc1.4D400C    13k video only          240p, mp4_dash
242 webm  244x240     25    |  606.50KiB  39k https | vp09.00.20.08  39k video only          240p, webm_dash
396 mp4   366x360     25    |  701.91KiB  45k https | av01.0.00M.08  45k video only          360p, mp4_dash
134 mp4   366x360     25    |  364.02KiB  23k https | avc1.4D4015    23k video only          360p, mp4_dash
18  mp4   366x360     25  2 | ≈  1.12MiB  72k https | avc1.42001E        mp4a.40.2       22k 360p
243 webm  366x360     25    |  979.65KiB  63k https | vp09.00.21.08  63k video only          360p, webm_dash
397 mp4   488x480     25    |    1.00MiB  66k https | av01.0.01M.08  66k video only          480p, mp4_dash
135 mp4   488x480     25    |  608.24KiB  39k https | avc1.4D401E    39k video only          480p, mp4_dash
244 webm  488x480     25    |    1.52MiB 100k https | vp09.00.30.08 100k video only          480p, webm_dash
22  mp4   732x720     25  2 | ≈  3.12MiB 200k https | avc1.64001F        mp4a.40.2       44k 720p
398 mp4   732x720     25    |    1.90MiB 124k https | av01.0.04M.08 124k video only          720p, mp4_dash
136 mp4   732x720     25    |    1.08MiB  71k https | avc1.4D401F    71k video only          720p, mp4_dash
247 webm  732x720     25    |    3.07MiB 201k https | vp09.00.31.08 201k video only          720p, webm_dash
```
NB: The specified `youtube` video is geo-fenced to the **US**, only...

`hp.exe` = `hola-proxy.windows-386.exe`, OS = **Win7 SP1 x86**

@chromer030 

Your posted log contains this error:
```console
CRED    : 2023/10/04 17:20:35 credservice.go:33: ERROR    Configuration bootstrap error: Post "https://client.hola.org/client_cgi/background_init?uuid=34b45c118d3340db938a76dceafbe4cf": context deadline exceeded. Retrying with the fallback mechanism...
```
which is **different to the one** I posted in the OP of this issue 😉 ; probably you're affected by something else; an online service I've used places `zagent2617.hola.org` to **Germany**; do other `hola` nodes work for you? I also don't have any issues connecting to German nodes (e.g. `https://zagent2618.hola.org:22222`), so will have to wait and see whether this is a Hola change pushed out gradually (I hope not 😜 ) ...

**Comment by chromer030** [comment]
@Snawoot @Vangelis66 

Thank you for your feedback, i appreciate it, if hola is OK on your side, so the issue is in my side obviously.
My internet is in severe restrictions and censorship maybe that the root of issue.

**Comment by Snawoot** [comment]
> @Snawoot @Vangelis66
> 
> Thank you for your feedback, i appreciate it, if hola is OK on your side, so the issue is in my side obviously. My internet is in severe restrictions and censorship maybe that the root of issue.

@chromer030 

That's unlikely. This error comes from hola backend, which is contacted via secure connection. So it's very unlikely censor has any ways to interfere with it other than completely blocking service, it can't make Hola send you "403 Auth failed" error to you.

Most likely you just hit some of their restrictions: request volume, datacenter IP and so on.

**Comment by chromer030** [comment]
@Snawoot 

> Most likely you just hit some of their restrictions: request volume, datacenter IP and so on.

Maybe that's because here too many people are using hola.

Is there anyway to enter the hola account in tool?

I created an account with temp mail to try.

**Comment by chromer030** [comment]
> This error comes from hola backend

Found the issue, installed hola chrome extenstion and got : unfortunately hola is not available in your country!

**Comment by Snawoot** [comment]
> > This error comes from hola backend
> 
> Found the issue, installed hola chrome extenstion and got : unfortunately hola is not available in your country!

Oh, interesting. Which country it is?

**Comment by chromer030** [comment]
> Oh, interesting. Which country it is?

Countries where Hola services are not available are: India, Iran, Iraq, Syria, Lebanon, Palestine, North Korea, Cuba, Sudan, Crimea region.

**Comment by chromer030** [comment]
Really thank you for your generosity and efforts to provide solutions. i appreciate it. ❤️

> Was that pure speculation, given that "here" is supposedly blocked by hola?

I thought that's the cause of issue, but it's not!
After a google search i found that Hola is an Israel based VPN company.
And Iran, Iraq, Syria, Lebanon and Palestine are serious enemies of Israel, that's because it's server-side blocked on these countries.

> If Your regime doesn't block its IP address

Almost every proxy and every VPN is blocked here, all main social medias are blocked : `Youtube, Instagram, Telegram, Whatsapp, Facebook, Twitter, Reddit, Tiktok and many more websites`

The internet censorship and filteration are very very severe.
The filtering system is an adaptation on [GFW](https://en.wikipedia.org/wiki/Great_Firewall) plus Russians DPI (deep packet injection) that's why non of VPNs are working.

One of the main challenges of people is to find a vpn to bypass the restrictions.

Most of protocols and ports are blocked or under harsh monitoring to auto-block.
The only method and protocol which works is Shadowsocks and similar protocols like Trojan, Vmess, Vless as they all are designed for bypassing GFW.

The regime is designing an interanet to fully cut internet access, something like North-Korea's one.
And because of this + many severe economical issues (High povery rate) the people are highly seeking immigration (as i seek it too), more than 15 millions are living abroad and that's increasing day to day)

I'm living in Iran, the freedom of Internet is a dream for people, something that for other people of the world is an ordinary thing. (Right to have access to Internet)

> FWIW, can you successfully use the other proxy tools offered by Snawoot ?

No, I tried, they are all blocked.

- My last kindly words:

If there are social & internet freedoms and economical/financial security in your country, please appreciate that and be grateful to your government.

Here people are getting killed by Regime for not having [Hijab](https://en.wikipedia.org/wiki/Hijab), here even there is no freedom & right to clothing!
The regime kills people brutally and control them by pauperizing everyone.
